web:
  image: golang
  # command: 
  ports:
    - "8080:8080"
  environment:
    - POSTGRES_HOST=192.168.0.4
    - POSTGRES_DBNAME=go_user_api
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker    
  links:
   - db
db:
  image: postgresql
